sudo: required
language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
  - '8'
  - '6'
  - '10'
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run codecov
notifications:
  email: false
